modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/pet-cemetery/issues"
license = "https://github.com/team-abnormals/pet-cemetery/blob/main/LICENSE.txt"

[[mods]]
    modId = "pet_cemetery"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "pet_cemetery:pet_collar"
    configBackground = "minecraft:textures/block/weathered_copper.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, hatsondogs"
    displayURL = "https://www.teamabnormals.com/mods/pet-cemetery"
    displayName = "Pet Cemetery"
    description = '''
    Bring back your fallen friends!
    '''

[[dependencies.pet_cemetery]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.pet_cemetery]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.pet_cemetery]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.1,)"
    ordering = "AFTER"
    side = "BOTH"